# -*- coding: utf-8 -*-
"""MedBuddy Application

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTlGoEF4f2QgRGBudBOW1wjny3IpdW6K
"""

# Import the Streamlit library, which is used to create our simple, clutter-free web user interface.
import streamlit as st

# Import the os module, allowing us to interact with the operating system (e.g., setting environment variables).
import os

# Import the tempfile module to create secure, temporary directories to store the user's uploaded PDF files.
import tempfile

# Import SimpleDirectoryReader from LlamaIndex to automatically read and parse the files inside our temporary directory.
from llama_index.core import SimpleDirectoryReader

# Import VectorStoreIndex from LlamaIndex, which converts our document text into a searchable mathematical vector database.
from llama_index.core import VectorStoreIndex

# Import Settings from LlamaIndex to configure our global artificial intelligence models (both the brain and the embedder).
from llama_index.core import Settings

# Import the Gemini class from LlamaIndex, allowing us to use Google's Gemini as the primary thinking/answering model.
from llama_index.llms.gemini import Gemini

# Import the GeminiEmbedding class, which translates our textbook text into numbers (vectors) that the computer can easily search.
from llama_index.embeddings.gemini import GeminiEmbedding

# Configure the fundamental settings of the Streamlit page, setting the browser tab title and the layout style to centered.
st.set_page_config(page_title="MedBuddy", layout="centered")

# Display the main, clear title at the top of the application web page.
st.title("MedBuddy: Medical Book Chatbot 🩺")

# Display a short, simple subtext explaining what the application does to the user.
st.write("Upload your medical textbook and ask questions. Powered by Gemini and RAG.")

# Create a sidebar in the Streamlit UI to keep the settings and file uploads separate from the main chat interface.
with st.sidebar:
    # Add a title to the sidebar to clearly indicate its purpose.
    st.header("Setup & Upload")

    # Create a password-type text input box asking the user for their Google Gemini API Key.
    api_key = st.text_input("Enter Google Gemini API Key:", type="password")

    # Create a file uploader widget in the sidebar that exclusively accepts PDF files.
    uploaded_file = st.file_uploader("Upload Medical Textbook (PDF)", type=["pdf"])

# Check if the user has provided an API key. If not, halt the application and wait for them to input it.
if not api_key:
    # Display an informative warning asking the user to provide their API key to proceed.
    st.warning("Please enter your Google Gemini API Key in the sidebar to start.")
    # Stop the execution of the rest of the script until the API key is provided.
    st.stop()

# Set the provided API key as an environment variable so LlamaIndex and Google's SDK can access it securely in the background.
os.environ["GOOGLE_API_KEY"] = api_key

# Configure the global LlamaIndex settings to use Google's Gemini 1.5 Flash model for generating text answers.
Settings.llm = Gemini(model="models/gemini-1.5-flash", api_key=api_key)

# Configure the global LlamaIndex settings to use Google's specific embedding model to convert text into searchable vectors.
Settings.embed_model = GeminiEmbedding(model_name="models/embedding-001", api_key=api_key)

# Check if a chat history list exists in the Streamlit session state; if not, initialize an empty list to remember the conversation.
if "messages" not in st.session_state:
    # Initialize the messages list inside the session state.
    st.session_state.messages = []

# Check if a query engine exists in the session state; if not, initialize it as None to be populated after a file is uploaded.
if "query_engine" not in st.session_state:
    # Initialize the query engine variable inside the session state.
    st.session_state.query_engine = None

# If a file has been uploaded by the user but hasn't been processed into a query engine yet, begin processing.
if uploaded_file is not None and st.session_state.query_engine is None:
    # Show a loading spinner on the screen so the user knows the application is working in the background.
    with st.spinner("Reading and Indexing your Medical Textbook... Please wait."):

        # Create a temporary directory on the computer to safely save the uploaded PDF without cluttering the system.
        with tempfile.TemporaryDirectory() as temp_dir:

            # Create a full file path inside the temporary directory using the uploaded file's original name.
            file_path = os.path.join(temp_dir, uploaded_file.name)

            # Open the newly created file path in write-binary mode to save the uploaded PDF data.
            with open(file_path, "wb") as f:
                # Write the actual byte data from the uploaded file into our local temporary file.
                f.write(uploaded_file.getbuffer())

            # Use LlamaIndex's SimpleDirectoryReader to look into our temporary directory and read the PDF file we just saved.
            documents = SimpleDirectoryReader(temp_dir).load_data()

            # Take the extracted documents and convert them into a mathematical Vector Store Index for rapid semantic searching.
            index = VectorStoreIndex.from_documents(documents)

            # Convert the newly created index into a query engine, allowing us to ask natural language questions against it.
            st.session_state.query_engine = index.as_query_engine()

            # Display a success message confirming that the PDF has been successfully processed and is ready for chatting.
            st.success("Textbook successfully indexed! You can now start asking questions.")

# Loop through all the messages currently saved in the session state's chat history.
for message in st.session_state.messages:
    # Render each message on the UI using Streamlit's chat_message feature, assigning the appropriate role (user or assistant).
    with st.chat_message(message["role"]):
        # Display the text content of the message using markdown formatting.
        st.markdown(message["content"])

# Display a chat input box at the bottom of the screen, waiting for the user to type a medical question.
if prompt := st.chat_input("Ask a question about your medical book..."):

    # Check if the query engine is ready (meaning a PDF has been uploaded and indexed). If not, ask the user to upload one.
    if st.session_state.query_engine is None:
        # Display an error message explaining that a PDF needs to be uploaded first.
        st.error("Please upload a PDF textbook in the sidebar first.")
    else:
        # Add the user's newly typed question to the chat history list in the session state.
        st.session_state.messages.append({"role": "user", "content": prompt})

        # Display the user's question immediately on the screen inside a chat bubble.
        with st.chat_message("user"):
            # Render the text of the user's question.
            st.markdown(prompt)

        # Create a chat bubble for the AI assistant and show a thinking spinner while the Gemini model formulates an answer.
        with st.chat_message("assistant"):
            # Display a spinner to indicate that the RAG process (retrieval and generation) is actively occurring.
            with st.spinner("Thinking and searching the textbook..."):

                # Pass the user's question to the LlamaIndex query engine, which searches the vector store and queries Gemini.
                # NOTE: This is where TruLens would intercept the query in a testing environment to evaluate Groundedness.
                response = st.session_state.query_engine.query(prompt)

                # Display the final generated answer from Gemini on the screen inside the assistant's chat bubble.
                st.markdown(response.response)

        # Save the AI assistant's generated answer to the chat history list so it persists on the screen.
        st.session_state.messages.append({"role": "assistant", "content": response.response})